name: deploy

# on:
#   push:
#     branches: [main] # on push to main branch

jobs:
  setup-and-deploy:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: recursive

      # Set up Python 3.8 environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      # Set up cache for pip
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
            
      # Get database library
      - name: Checkout database library
        uses: actions/checkout@v2
        with:
          repository: tree-plenish/tech_team_database
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: './tech_team_database'

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Elastic Beanstalk CLI version
      - name: Get EB CLI version
        run: |
          ls
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version
      # Create the Elastic Beanstalk application
      - name: Create EBS application
        run: |
          eb init -p python-3.8 <APP_NAME_HERE> --region us-east-2
      # Deploy to (or Create) the Elastic Beanstalk environment
      - name: Create environment & deploy
        run: |
          (eb use <ENVIRONMENT_NAME_HERE> && eb status <ENVIRONMENT_NAME_HERE> && eb deploy) || eb create <ENVIRONMENT_NAME_HERE>